### ISSUE TITLE
[Issue]:  fatal error: 'hip/hip_fp8.h' file not found

### ISSUE THREAD

**Issue by shahizat** [ROCm/hipBLASLt#1210]
### Problem Description

Hello, when I run command to build from the source : 

`./install.sh -idc --legacy_hipblas_direct`

It shows below output after a while :

`  40 | #include <hip/hip_fp8.h>
      |          ^~~~~~~~~~~~~~~
In file included from /home/admin2/hipBLASLt/build/release/virtualenv/lib/python3.12/site-packages/Tensile/Source/lib/source/hip/HipSolutionAdapter.cpp:34:
In file included from /home/admin2/hipBLASLt/build/release/virtualenv/lib/python3.12/site-packages/Tensile/Source/lib/include/Tensile/hip/HipSolutionAdapter.hpp:29:
In file included from /home/admin2/hipBLASLt/build/release/virtualenv/lib/python3.12/site-packages/Tensile/Source/lib/include/Tensile/AMDGPU.hpp:29:
In file included from /home/admin2/hipBLASLt/build/release/virtualenv/lib/python3.12/site-packages/Tensile/Source/lib/include/Tensile/Tensile.hpp:41:
In file included from /home/admin2/hipBLASLt/build/release/virtualenv/lib/python3.12/site-packages/Tensile/Source/lib/include/Tensile/KernelArguments.hpp:35:
In file included from /home/admin2/hipBLASLt/build/release/virtualenv/lib/python3.12/site-packages/Tensile/Source/lib/include/Tensile/DataTypes.hpp:40:
/home/admin2/hipBLASLt/build/release/virtualenv/lib/python3.12/site-packages/Tensile/Source/lib/include/Tensile/DataTypes_Float8_BFloat8.hpp:40:10: fatal error: 'hip/hip_fp8.h' file not found
   40 | #include <hip/hip_fp8.h>
      |          ^~~~~~~~~~~~~~~
1 error generated when compiling for gfx1100.
1 error generated when compiling for gfx1100.
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:174: Tensile/lib/CMakeFiles/TensileHost.dir/source/KernelArguments.cpp.o] Error 1
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:76: Tensile/lib/CMakeFiles/TensileHost.dir/source/AMDGPU.cpp.o] Error 1
1 error generated when compiling for gfx1100.
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:202: Tensile/lib/CMakeFiles/TensileHost.dir/source/MLFeatures.cpp.o] Error 1
1 error generated when compiling for gfx1100.
1 error generated when compiling for gfx1100.
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:314: Tensile/lib/CMakeFiles/TensileHost.dir/source/hip/HipHardware.cpp.o] Error 1
1 error generated when compiling for gfx1100.
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:258: Tensile/lib/CMakeFiles/TensileHost.dir/source/Tensile.cpp.o] Error 1
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:146: Tensile/lib/CMakeFiles/TensileHost.dir/source/EmbeddedLibrary.cpp.o] Error 1
1 error generated when compiling for gfx1100.
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:90: Tensile/lib/CMakeFiles/TensileHost.dir/source/ContractionProblem.cpp.o] Error 1
1 error generated when compiling for gfx1100.
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:300: Tensile/lib/CMakeFiles/TensileHost.dir/source/hip/HipSolutionAdapter.cpp.o] Error 1
1 error generated when compiling for gfx1100.
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:104: Tensile/lib/CMakeFiles/TensileHost.dir/source/ContractionSolution.cpp.o] Error 1
1 error generated when compiling for gfx1100.
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:286: Tensile/lib/CMakeFiles/TensileHost.dir/source/msgpack/MessagePack.cpp.o] Error 1
make[2]: Leaving directory '/home/admin2/hipBLASLt/build/release'
make[1]: *** [CMakeFiles/Makefile2:294: Tensile/lib/CMakeFiles/TensileHost.dir/all] Error 2
make[1]: Leaving directory '/home/admin2/hipBLASLt/build/release'
make: *** [Makefile:166: all] Error 2`

### Operating System

22.04.4 LTS (Jammy Jellyfish)

### CPU

 AMD Ryzen Threadripper 7960X 24-Cores

### GPU

AMD Radeon RX 7900 XTX

### Other

ROCm Version: 6.1.3.60103-122~22.04

### ROCm Version

ROCm 5.6.0

**Comment by m-kim** [comment]
Can you try updating to ROCm 6.2 or higher?

**Comment by shahizat** [comment]
hello @m-kim , yes I did, and it helped😊, thank you!
