### ISSUE TITLE
[Issue]: Where is the `Module.addInst` method defined?

### ISSUE THREAD

**Issue by 103yiran** [ROCm/hipBLASLt#1223]
### Problem Description

The `module.addInst` is used in [KernelWriterAssembly.py](https://github.com/ROCm/hipBLASLt/blob/develop/tensilelite/Tensile/KernelWriterAssembly.py) and many files under [Components](https://github.com/ROCm/hipBLASLt/tree/develop/tensilelite/Tensile/Components). But I can't find where it is defined. So far it looks like the Tensile repository is at [Tensile/Code.py#L108](https://github.com/ROCm/Tensile/blob/develop/Tensile/Code.py#L108), but not in tensilelite.

### Operating System

Ubuntu 20.04.6 LTS

### CPU

Intel® Core™ i5-9500 CPU @ 3.00GHz × 6 

### GPU

AMD Instinct MI250X

### ROCm Version

ROCm 5.7.1

**Comment by ppanchad-amd** [comment]
Hi @103yiran. Internal ticket has been created to assist with your issue. Thanks!

**Comment by jichangjichang** [comment]
addInst() is deprecated and some usused code section still refer to addInst(). Please just ignore it.
