### ISSUE TITLE
use of min(int, size_t) causes ambiguity with clang

### ISSUE THREAD

**Issue by yxsamliu** [ROCm/hipBLASLt#1227]
at https://github.com/ROCm/hipBLASLt/blob/develop/library/src/amd_detail/rocblaslt/src/tensile_host.cpp#L2923

and https://github.com/ROCm/hipBLASLt/blob/develop/library/src/amd_detail/rocblaslt/src/tensile_host.cpp#L2898

there is code 

```
auto algoCount       = min(requestedAlgoCount, solutions.size());
```

requestedAlgoCount is int type, solutions.size() is size_t (unsigned long) type. This causes compilation error for clang trunk due to recent PR (https://github.com/llvm/llvm-project/pull/82956) and is blocking the fix gets into amd-staging branch.

To fix this, change  https://github.com/ROCm/hipBLASLt/blob/develop/library/src/amd_detail/rocblaslt/src/tensile_host.cpp#L2923
and https://github.com/ROCm/hipBLASLt/blob/develop/library/src/amd_detail/rocblaslt/src/tensile_host.cpp#L2898 to be

```
auto algoCount       = min(static_cast<size_t>(requestedAlgoCount), solutions.size());
```

**Comment by darren-amd** [comment]
Hi @yxsamliu,

Thanks for the suggestion, this has been changed as you suggested [here](https://github.com/ROCm/hipBLASLt/commit/1342b7a870ff16107a0248602e4655addeb04965).
