### ISSUE TITLE
[Issue]: Could not find a package configuration file provided by "hipblas-common"

### ISSUE THREAD

**Issue by amd-hhashemi** [ROCm/hipBLASLt#1281]
### Problem Description

CMake Error at CMakeLists.txt:266 (find_package):
  Could not find a package configuration file provided by "hipblas-common"
  with any of the following names:

    hipblas-commonConfig.cmake
    hipblas-common-config.cmake

  Add the installation prefix of "hipblas-common" to CMAKE_PREFIX_PATH or set
  "hipblas-common_DIR" to a directory containing one of the above files.  If
  "hipblas-common" provides a separate development package or SDK, be sure it
  has been installed.

### Operating System

Ubuntu

### CPU

AMD Ryzen 9 7950X 16-Core Processor

### GPU

AMD Instinct MI250X

### ROCm Version

ROCm 5.7.1

### Steps to Reproduce

./install.sh -idc
in a fresh rocm/pytorch:latest docker

**Comment by harkgill-amd** [comment]
Hi @amd-hhashemi, when building for ROCm <= 6.2, please pass the `--legacy_hipblas_direct` flag to `install.sh` as done below
```
./install.sh -idc --legacy_hipblas_direct
```
This will avoid searching for the `hipblas-common` package which will be available in an upcoming ROCm release. Another option is to manually build the package and then build `hipblaslt` by running the following inside the hipblaslt folder:
```
git clone https://github.com/ROCm/hipBLAS-common.git
cd hipBLAS-common
python3 ./rmake.py --install
cd ..
./install.sh -idc
```

**Comment by amd-hhashemi** [comment]
closed
