### ISSUE TITLE
FP64 missing in the table

### ISSUE THREAD

**Issue by jinz2014** [ROCm/hipBLASLt#1297]
A | B | C | D | Compute(Scale)
-- | -- | -- | -- | --
fp32 | fp32 | fp32 | fp32 | fp32
fp16 | fp16 | fp16 | fp16 | fp32
fp16 | fp16 | fp16 | fp32 | fp32
bf16 | bf16 | bf16 | bf16 | fp32
fp8/bf8 | fp8/bf8 | fp32 | fp32 | fp32
fp8/bf8 | fp8/bf8 | fp16 | fp16 | fp32
fp8/bf8 | fp8/bf8 | bf16 | bf16 | fp32
fp8/bf8 | fp8/bf8 | fp8 | fp8 | fp32
fp8/bf8 | fp8/bf8 | bf8 | bf8 | fp32
int8 | int8 | int8 | int8 | int32

**Comment by jinz2014** [comment]
Will you publish performance results of GEMM using the library on gf90a devices in README ?

**Comment by jinz2014** [comment]
MI210 GPU

Are these results similar to  yours ?
 
shape: (4096, 4096) x (4096, 4096)

test fp32
651.934964 GFLOP/s

test fp16 (compute type fp32) 
48.182494 GFLOP/s

test bfloat16 (compute type fp32) 
48.524520 GFLOP/s

test int8 
1.803397 TOP/s

**Comment by ppanchad-amd** [comment]
Hi @jinz2014. Internal ticket has been created to assist with your issue. Thanks!

**Comment by jinz2014** [comment]
Please see a reproducer: https://github.com/zjin-lcf/HeCBench/tree/master/src/blas-gemmEx2-hip

The results may vary slightly across runs.

**Comment by tcgu-amd** [comment]
Hi @jinz2014, unfortunately we are not able to provide users with any benchmark results. As for your original question, thanks for catching that; F64 is supported except on gfx908. Thanks!

**Comment by jinz2014** [comment]
Thanks for developing the library that allows portability from CUDA to HIP.
