### ISSUE TITLE
[Issue]: [Documentation] Document gfx908 support

### ISSUE THREAD

**Issue by IMbackK** [ROCm/hipBLASLt#1299]
### Problem Description

Since 938900a10d0c433eb8b90c2a3b65ba70ed39a91b has landed git hipblaslt supports gfx908, but this is not documented in the readme.

Side Note: the maximum rocm version that can be specified in in the drop down when repoting is severly out of date as it offers maximally rocm 5.7

### Operating System

Any

### CPU

N/A

### GPU

AMD Instinct MI100

### ROCm Version

ROCm 5.7.1

**Comment by ppanchad-amd** [comment]
Hi @IMbackK. Internal ticket has been created to fix this issue. Thanks!

**Comment by LunNova** [comment]
I wasn't able to get gfx908 support to build on 3c44762350b2386f3a0f448cfb732f3eee380f2b

https://github.com/ROCm/hipBLASLt/pull/327#issuecomment-2504250067

**Comment by IMbackK** [comment]
It compiles and works fine for me @ 6655405569ec47ec8637b743f48713e45f299d8d (but performance is very poor), if latest master dose not compile please file a sperate issue for that and dont hijack this one.

**Comment by tcgu-amd** [comment]
Hi @IMbackK, thank you for reaching out and sorry for the late response. I have raised a PR to update the readme https://github.com/ROCm/hipBLASLt/pull/1468. Thanks!

**Comment by IMbackK** [comment]
great @tcgu-amd, thank you.

**Comment by tcgu-amd** [comment]
Hi, @IMbackK, a quick update -- support for gfx908 is still currently experimental, and updates to the docs will be merged once we officially supports it. I will be closing this issue for now and track it through the PR. Thanks!
