### ISSUE TITLE
cublasLtMatrixTransform() equivalent 

### ISSUE THREAD

**Issue by yves-renier** [ROCm/hipBLASLt#133]
Hello, 
I did not find any reference of an equivalent of the function [cublasLtMatrixTransform()](https://docs.nvidia.com/cuda/cublas/index.html#cublasltmatrixtransform) in hipBLASLt.
Is there any plan to make one available ?

**Comment by ewof** [comment]
would be nice
latest bitsandbytes can't be hipified because of use of cublasLtMatrixTransform()

**Comment by jichangjichang** [comment]
No plan so far.
The transpose operation can be set through cublasLtMatmulDescSetAttribute() before calling cublasLtMatmul().

**Comment by ppanchad-amd** [comment]
@jichangjichang Is there still no plans to implement equivalent of the function cublasLtMatrixTransform() in hipBLASLt? If not, please advise if I can close ticket as not planned. Thanks!

**Comment by jichangjichang** [comment]
https://rocm.docs.amd.com/projects/hipBLASLt/en/latest/api-reference.html#hipblasltmatrixtransform

**Comment by darren-amd** [comment]
Hi @yves-renier,

This has been added in hipBLASLt, as mentioned above. You can find the documentation here: [hipBLASLt Matrix Transform](https://rocm.docs.amd.com/projects/hipBLASLt/en/latest/api-reference.html#hipblasltmatrixtransform), thanks for the suggestion!
