### ISSUE TITLE
question about FP16 compute_type

### ISSUE THREAD

**Issue by jinz2014** [ROCm/hipBLASLt#1385]
No algorithm was found for the case: a/b type=FP16, c type=FP16, compute_type=FP16.  Is it supported in the library ?

**Comment by harkgill-amd** [comment]
Hi @jinz2014, FP16 is not supported as a compute type. Please see the [datatype support table](https://github.com/ROCm/hipBLASLt?tab=readme-ov-file#hipblaslt) in the README for more information on supported compute types.

**Comment by jinz2014** [comment]
Ok. Will it be supported ?

**Comment by harkgill-amd** [comment]
Let me confirm this with the team and get back to you.

**Comment by harkgill-amd** [comment]
https://github.com/ROCm/hipBLASLt/pull/1263 introduces support for fallback from fp16 to fp32. fp16 support is being considered for a future release.
