### ISSUE TITLE
[Issue]: "unused" dependencies in requirements.txt

### ISSUE THREAD

**Issue by AngryLoki** [ROCm/hipBLASLt#1441]
### Problem Description

Hi, 

At this moment https://github.com/ROCm/hipBLASLt/blob/develop/tensilelite/requirements.txt in tensilelite adds `simplejson`, `ujson` and `orjson` libraries. However in the source code only yaml and msgpack are supported (and this is not the only place, there are other places which support only `.yaml` or `.dat`):
https://github.com/ROCm/hipBLASLt/blob/e13e13351a8167fefec51974786f3822a6e38281/tensilelite/Tensile/TensileCreateLibrary.py#L715-L716

Also `packaging` seems to be unused (at least directly). Original Tensile library does not use these libraries - https://github.com/ROCm/Tensile/blob/develop/requirements.txt. 

These libraries require additional steps to build hipBLASLt in controlled network-isolated environments (see also https://github.com/ROCm/hipBLASLt/issues/1396#issuecomment-2506432129). Could you remove them?

### ROCm Version

ROCm 6.3.0

**Comment by ppanchad-amd** [comment]
Hi @AngryLoki. Internal ticket has been created to fix this issue. Thanks!

**Comment by jichangjichang** [comment]
json is used for LogicFormat.
https://github.com/ROCm/hipBLASLt/blob/e13e13351a8167fefec51974786f3822a6e38281/tensilelite/Tensile/TensileCreateLibrary.py#L713C1-L714C98

**Comment by AngryLoki** [comment]
Noted, I missed that part. Could you still select a single json reader? `requirements.txt` installs all of them, maybe it was performance bottleneck, but anyways only one library is used.

**Comment by lucbruni-amd** [comment]
Hi @AngryLoki,

These json libraries are indeed used here:

https://github.com/ROCm/hipBLASLt/blob/e13e13351a8167fefec51974786f3822a6e38281/tensilelite/Tensile/TensileCreateLibrary.py#L713-L714

As for `packaging`, I could not build after simply removing it as it is referenced here:

https://github.com/ROCm/hipBLASLt/blob/e13e13351a8167fefec51974786f3822a6e38281/tensilelite/Tensile/Parallel.py#L35-L37

As for your question above, I was able to build with a single reader, feel free to give this a try as desired for your environment.

Feel free to open another issue if you have further concerns. Thanks!
