### ISSUE TITLE
hipblasLtMatmul api usage

### ISSUE THREAD

**Issue by Cydia2018** [ROCm/hipBLASLt#313]
I would like to ask whether it is necessary to call`hipblasLtMatmulAlgoGetHeuristic()` to search algo before executing `hipblasLtMatmul()`?
When I set the three parameters of `hipblasLtMatmulAlgo_t *algo`, `void *workspace`, `size_t workspaceSizeInBytes` of `hipblasLtMatmul()` to nullptr, nullptr, and 0 respectively, the segment fault occurred.

**Comment by KKyang** [comment]
Yes, it is necessary. Here is the sample,
https://github.com/ROCmSoftwarePlatform/hipBLASLt/blob/a103f27d91f0dcd3abdcf262c18a601172b2d3ea/clients/samples/gemm/sample_hipblaslt_gemm.cpp#L153

or you can use ``getAllAlgos`` to get the solutions.
https://github.com/ROCmSoftwarePlatform/hipBLASLt/blob/a103f27d91f0dcd3abdcf262c18a601172b2d3ea/clients/samples/gemm_get_all_algos/sample_hipblaslt_gemm_get_all_algos.cpp#L103

**Comment by ppanchad-amd** [comment]
@Cydia2018 Do you still need assistance with this ticket? If not, please close the ticket? Thanks!

**Comment by ppanchad-amd** [comment]
Hi @Cydia2018. Hopefully your issue is resolved. Closing ticket. If you still need assistance, please feel free to re-open ticket. Thanks!
