### ISSUE TITLE
Install guide for non-root user

### ISSUE THREAD

**Issue by jinz2014** [ROCm/hipBLASLt#618]
Can you please provide build instructions for non-root users ?

```

Successfully installed Tensile-4.33.0 msgpack-1.0.7

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python3 -m pip install --upgrade pip
-- Adding /path/to/hipBLASLt/build/virtualenv to CMAKE_PREFIX_PATH
-- The C compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at build/virtualenv/lib/python3.10/site-packages/Tensile/Source/lib/CMakeLists.txt:105 (find_package):
  By not providing "Findmsgpack.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "msgpack", but
  CMake did not find one.

  Could not find a package configuration file provided by "msgpack" with any
  of the following names:

    msgpackConfig.cmake
    msgpack-config.cmake

  Add the installation prefix of "msgpack" to CMAKE_PREFIX_PATH or set
  "msgpack_DIR" to a directory containing one of the above files.  If
  "msgpack" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by KKyang** [comment]
Maybe it's the same problem? https://github.com/ROCm/hipBLASLt/issues/677

**Comment by zichguan-amd** [comment]
Hi @jinz2014, can you try using `-d` as suggested in https://github.com/ROCm/hipBLASLt/issues/677?

**Comment by jinz2014** [comment]
The command assumes that a user has root permission.

./install.sh -d

[  8%] Building C object CMakeFiles/msgpackc.dir/src/objectc.c.o
[ 16%] Building C object CMakeFiles/msgpackc.dir/src/unpack.c.o
[ 25%] Building C object CMakeFiles/msgpackc.dir/src/version.c.o
[ 33%] Building C object CMakeFiles/msgpackc.dir/src/vrefbuffer.c.o
[ 41%] Building C object CMakeFiles/msgpackc.dir/src/zone.c.o
[ 50%] Linking C shared library libmsgpackc.so
[ 50%] Built target msgpackc
[ 58%] Building C object CMakeFiles/msgpackc-static.dir/src/objectc.c.o
[ 66%] Building C object CMakeFiles/msgpackc-static.dir/src/unpack.c.o
[ 75%] Building C object CMakeFiles/msgpackc-static.dir/src/version.c.o
[ 83%] Building C object CMakeFiles/msgpackc-static.dir/src/vrefbuffer.c.o
[ 91%] Building C object CMakeFiles/msgpackc-static.dir/src/zone.c.o
[100%] Linking C static library libmsgpackc.a
[100%] Built target msgpackc-static

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

**Comment by zichguan-amd** [comment]
If you have all the dependencies then you can try building manually with cmake, see the docs here: https://rocm.docs.amd.com/projects/hipBLASLt/en/latest/installation.html#manual-build-all-supported-platforms. You can choose to install in a directory that does not require sudo permission with `-DCMAKE_INSTALL_PREFIX=<path>`.
