### ISSUE TITLE
[Issue]: Missing tensile Benchmark Problem config files

### ISSUE THREAD

**Issue by IMbackK** [ROCm/hipBLASLt#784]
The tensile benchmark config files for hipblaslt seam to be missing, they also dont seem to be in the Tensile git repo (unlike rocblas)
Please provide the yaml benchmark configurations for tensilelite.

**Comment by ppanchad-amd** [comment]
Hi @IMbackK. Apologies for the delayed response. Internal ticket has been created to assist with your issue. Thanks!

**Comment by darren-amd** [comment]
Hi @IMbackK,

Thanks for the suggestion! I spoke with the internal team, and unfortunately this is not currently in our roadmap.

**Comment by IMbackK** [comment]
In this case i would request that the fact that hipblaslt is NOT open source in accordance to the OSI definition of open source is correctly documented.

Without the benchmark files hipblaslt files sutch as aquavanjaram_Cijk_Ailk_Bjlk_B8B8S_BH_BiasSHB_AmaxD_HAS_SAB_SCD_SAV_UserArgs.yaml fail the open source definition section 2: "[...] The source code must be the preferred form in which a programmer would modify the program. Deliberately obfuscated source code is not allowed. Intermediate forms such as the output of a preprocessor or translator are not allowed."
see https://opensource.org/osd 

as these files are generated by the tensilelight scripts based on the benchmark.yaml files and without thair source it is impossible to port hipblaslt to other devices or add operators makeing hipblaslt unchangeable on the face of it.

**Comment by jichangjichang** [comment]
All the configurations of each sizes of aquavanjaram_Cijk_Ailk_Bjlk_B8B8S_BH_BiasSHB_AmaxD_HAS_SAB_SCD_SAV_UserArgs.yaml for each size can be directly found in its content.

**Comment by IMbackK** [comment]
Sure, but in order to change the configurations you would not change the logic files like aquavanjaram_Cijk_Ailk_Bjlk_B8B8S_BH_BiasSHB_AmaxD_HAS_SAB_SCD_SAV_UserArgs.yaml (since that do sent make sense really, the point of tensile to to make the right choices in there) you would change the benchmark files and rerun the benchmarks on a mi3xx. Thus the logic files cant be considered the preferred form for editing.

The fact that it is possible to reverse engineer the benchmark files based on the logic files dose not change this.
