### ISSUE TITLE
Inputs in `GemmInputs` should be pointers to `const`

### ISSUE THREAD

**Issue by atamazov** [ROCm/hipBLASLt#832]
Here:
https://github.com/ROCm/hipBLASLt/blob/65f51697f59616fd17e901d4bef7cfaa225b858a/library/include/hipblaslt-ext.hpp#L132-L137

Otherwise we have to provide a workaround in MIOpen.

**Comment by KKyang** [comment]
https://github.com/ROCm/hipBLASLt/pull/846
merged

**Comment by atamazov** [comment]
@KKyang Thenks. How the user of the library will detect if workaround (like const_cast that we use currently) is needed or not? Can we use hipBlasLt version number for this purpose?

**Comment by atamazov** [comment]
@KKyang Ping https://github.com/ROCm/hipBLASLt/issues/832#issuecomment-2197354615
