### ISSUE TITLE
[Issue]: Tensile generalize linux distro handling

### ISSUE THREAD

**Issue by trixirt** [ROCm/hipBLASLt#908]
### Problem Description

This issue in main Tensile project also effects hipBLASLt's copy of Tensile
[Tensile #1969
](https://github.com/ROCm/Tensile/issues/1969)

### Operating System

Fedora Rawhide

### CPU

x86_64

### GPU

AMD Instinct MI210

### ROCm Version

ROCm 5.7.1

**Comment by LunNova** [comment]
What's the relationship between Tensilelite in this repo and https://github.com/ROCm/Tensile/?
Are Linux distro packagers expected to have two different things both called Tensile in a complete ROCm install, with different version numbers, at different locations?

The buildscript for hipBLASLt seems to expect to use exactly Tensile 4.33.0 but the code shipped in a subfolder in this repo doesn't match the code at https://github.com/ROCm/Tensile/blob/rocm-5.2.3/CHANGELOG.md

It's not clear how distros are intended to package this. Without making changes the build script requires an internet connection as it uses `pip` to set up the virtualenv, and this is bad for reproducible or offline builds.

**Comment by trixirt** [comment]
It is possible to build without network, but it isn't pretty.
https://src.fedoraproject.org/rpms/hipblaslt/blob/rawhide/f/hipblaslt.spec#_95
hipblaslt's fork of tensile never gets installed on fedora.

**Comment by tcgu-amd** [comment]
Hi @trixirt, unfortunately, we do not plan on supporting this feature for now. Please see this  https://github.com/ROCm/Tensile/pull/1971#issuecomment-2444912900 for more details. Thanks!
